### PR TITLE
Add opt-in autocomplete for emoji

### PR DESCRIPTION
**Pull request by omarestrella**

### CODE REVIEW

**Comment by areese159** [comment]
Why not use a block component and yeild the textarea instead of placing it next to it and just look for child that is textarea or input?

**Comment by omarestrella** [comment]
@areese159: Because I am a super dummy and didn't think about using it as a block.

**Comment by areese159** [comment]
😄

**Comment by areese159** [comment]
What's the status of this PR? We have been waiting for over two years now for its completion....

**Comment by omarestrella** [comment]
> What's the status of this PR? We have been waiting for over two years now for its completion....

Soon.

**Pull request closed without merging**
